### ISSUE TITLE
hubot conf set seems to not work

### ISSUE THREAD

**Issue by msound** [anishathalye/hubot-conf#1]
I am using Hubot with Slack, and the conf set command does not seem to work. I am getting no response.

**Comment by msound** [comment]
After scratching my head for a couple of hours, figured out that my OSX is converting double quotes into smart double quotes. This was making the regex fail, and the `conf set` command never fired.

You can disable smart quotes in OSX by following [this article](http://osxdaily.com/2014/04/10/change-quote-style-mac-os-x/)

**Comment by anishathalye** [comment]
I was just about to type a response, but it looks like you answered your own question. :)

Hmm, I guess something to think about in the future is whether to account for smart quotes.

**Comment by anishathalye** [comment]
Btw, if you want to see an example of this being used in practice, you could take a look at [hackmit-hackbot](https://github.com/techx/hackmit-hackbot) where it's deployed, or [hubot-group](https://github.com/anishathalye/hubot-group) or [hubot-shortcut](https://github.com/anishathalye/hubot-shortcut) where it's used.

The docs for hubot-conf aren't that good right now, I haven't had much time to spend on it (PRs are more than welcome.)

**Comment by msound** [comment]
@anishathalye I wouldn't bother. It's not your module's fault as much as OSX screwing up double quotes. You really need to squint to see the difference between the two double quotes.

Really cool hubot plugin btw!

**Comment by msound** [comment]
I am using hubot-shortcut actually, and ran into this problem with hubot-conf.

BTW, I tried doing `hubot conf set shortcut.qa "hubot jenkins build qa"` and my Slack promptly converted `shortcut.qa` into a hyperlink (im guessing `.qa` is ccTLD for Qatar).

So, I gave up trying to configure stuff from slack. Doing it directly on `hubot>` prompt.

**Comment by anishathalye** [comment]
Yeah, it's annoying that Slack does that. #2 should help people work around that.

**Comment by anishathalye** [comment]
@msound FYI, this is fixed now in hubot-conf 1.2.0 (fixed in 30af1b34925fa385d7a3f5b581720695f819d268).
